---
swagger: "2.0"
info:
  x-ibm-name: "mock-2"
  title: "mock-2"
  version: "1.0.1"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/mock-2"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  erdemir-oauth:
    type: "oauth2"
    description: ""
    flow: "application"
    scopes: {}
    tokenUrl: "https://192.168.220.5/ibm/sb/erdemir-oauth/oauth2/token"
    x-tokenIntrospect:
      url: ""
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        title: "gatewayscript"
        version: "1.0.0"
        source: "let response = {}\nlet body = {}\nbody.code = 200\nbody.message =\
          \ \"OK-2\"\nbody.version = apim.getvariable(\"api.version\")\nresponse.body\
          \ = body\napim.setvariable('message.body', response,'set')"
  phase: "realized"
paths:
  /health:
    get:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/response-object"
definitions:
  response-object:
    properties:
      code:
        type: "integer"
        format: "int32"
        example: "200"
      message:
        type: "string"
        example: "Success"
    additionalProperties: false
tags: []
